[package]
name = "ro-rust-v2"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
pretty_assertions = "1.4.0"


[features]
unit = []
integration = []
full = ["unit", "integration"]
